servers:
    - name: Freenode
      profile: freenode-ssl
      channels:
        - #southlondonmakerspace
      nick: Makerbot
      userName: Makerbot
      realName: IRC bot for #southlondonmakerspace
      password: anything
apps:
    - default
database:
    type: mongodb
    name: makerbot
