servers:
    - name: Freenode
      profile: freenode
      channels:
        - "#southlondonmakerspace"
      nick: Makerbot
      userName: Makerbot
      realName: IRC bot
      password: anything
      autoConnect: false
apps:
    - default
    - error
database:
    type: mongodb
    name: makerbot
